### ISSUE TITLE
Api doc- badge not readable

### ISSUE THREAD

**Issue by JesusTheHun** [LiskArchive/lisk-legacy-docs#381]
Tiny display bug on https://lisk.io/documentation/lisk-core/api-mainnet.html, the badge is not readable on mobile, as seen below

![8DA83165-6549-4C98-959A-03093A5FC717](https://user-images.githubusercontent.com/94478/71187290-14993f80-227f-11ea-90db-2deb471f21e8.png)

**Comment by JesusTheHun** [comment]
I checked on desktop, the issue is present too.

**Comment by Tschakki** [comment]
Should be fixed now :)

**Comment by JesusTheHun** [comment]
Lol that's a dirty fix! We can still see the borders (because of inset shadow I believe) and the corners.
